version: "3.7"
services:
  namenode:
    image: rishychawla/hdfs
    volumes:
      - ./src:/src
    network: host
    ports:
      - "9090:9090"
    environment:
      - NAMENODE_NAME=NameNode
      - NAMENODE_PORT=9090
      - NAMENODE_IP=namenode
    tty: true

  dataNode1:
    image: rishychawla/hdfs
    volumes:
      - ./src:/src
    tty: true
    environment:
      - NODE_NAME=DataNode1
      - NODE_ID=0
      - NODE_PORT=9092
      - NAMENODE_IP=namenode
      - NAMENODE_PORT=9090
      - NAMENODE_NAME=NameNode
    ports:
      - "9092:9092"

  dataNode2:
    image: rishychawla/hdfs
    volumes:
      - ./src:/src
    tty: true
    environment:
      - NODE_NAME=DataNode2
      - NODE_ID=1
      - NODE_PORT=9093
      - NAMENODE_IP=namenode
      - NAMENODE_PORT=9090
      - NAMENODE_NAME=NameNode
    ports:
      - "9093:9093"

  dataNode3:
    image: rishychawla/hdfs
    volumes:
      - ./src:/src
    tty: true
    environment:
      - NODE_NAME=DataNode3
      - NODE_ID=2
      - NODE_PORT=9094
      - NAMENODE_IP=namenode
      - NAMENODE_PORT=9090
      - NAMENODE_NAME=NameNode
    ports:
      - "9094:9094"
