// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ds/hdfs/list.proto

package com.google.protobuf;

public final class ListProto {
  private ListProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ListFilesResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .ds.hdfs.ListFilesResponse.File files = 1;
    /**
     * <code>repeated .ds.hdfs.ListFilesResponse.File files = 1;</code>
     */
    java.util.List<com.google.protobuf.ListProto.ListFilesResponse.File> 
        getFilesList();
    /**
     * <code>repeated .ds.hdfs.ListFilesResponse.File files = 1;</code>
     */
    com.google.protobuf.ListProto.ListFilesResponse.File getFiles(int index);
    /**
     * <code>repeated .ds.hdfs.ListFilesResponse.File files = 1;</code>
     */
    int getFilesCount();
    /**
     * <code>repeated .ds.hdfs.ListFilesResponse.File files = 1;</code>
     */
    java.util.List<? extends com.google.protobuf.ListProto.ListFilesResponse.FileOrBuilder> 
        getFilesOrBuilderList();
    /**
     * <code>repeated .ds.hdfs.ListFilesResponse.File files = 1;</code>
     */
    com.google.protobuf.ListProto.ListFilesResponse.FileOrBuilder getFilesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ds.hdfs.ListFilesResponse}
   */
  public static final class ListFilesResponse extends
      com.google.protobuf.GeneratedMessage
      implements ListFilesResponseOrBuilder {
    // Use ListFilesResponse.newBuilder() to construct.
    private ListFilesResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ListFilesResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ListFilesResponse defaultInstance;
    public static ListFilesResponse getDefaultInstance() {
      return defaultInstance;
    }

    public ListFilesResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ListFilesResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                files_ = new java.util.ArrayList<com.google.protobuf.ListProto.ListFilesResponse.File>();
                mutable_bitField0_ |= 0x00000001;
              }
              files_.add(input.readMessage(com.google.protobuf.ListProto.ListFilesResponse.File.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          files_ = java.util.Collections.unmodifiableList(files_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.protobuf.ListProto.internal_static_ds_hdfs_ListFilesResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.protobuf.ListProto.internal_static_ds_hdfs_ListFilesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.protobuf.ListProto.ListFilesResponse.class, com.google.protobuf.ListProto.ListFilesResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<ListFilesResponse> PARSER =
        new com.google.protobuf.AbstractParser<ListFilesResponse>() {
      public ListFilesResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ListFilesResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ListFilesResponse> getParserForType() {
      return PARSER;
    }

    public interface FileOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string fileName = 1;
      /**
       * <code>required string fileName = 1;</code>
       */
      boolean hasFileName();
      /**
       * <code>required string fileName = 1;</code>
       */
      java.lang.String getFileName();
      /**
       * <code>required string fileName = 1;</code>
       */
      com.google.protobuf.ByteString
          getFileNameBytes();
    }
    /**
     * Protobuf type {@code ds.hdfs.ListFilesResponse.File}
     */
    public static final class File extends
        com.google.protobuf.GeneratedMessage
        implements FileOrBuilder {
      // Use File.newBuilder() to construct.
      private File(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private File(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final File defaultInstance;
      public static File getDefaultInstance() {
        return defaultInstance;
      }

      public File getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private File(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                fileName_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.protobuf.ListProto.internal_static_ds_hdfs_ListFilesResponse_File_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.protobuf.ListProto.internal_static_ds_hdfs_ListFilesResponse_File_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.protobuf.ListProto.ListFilesResponse.File.class, com.google.protobuf.ListProto.ListFilesResponse.File.Builder.class);
      }

      public static com.google.protobuf.Parser<File> PARSER =
          new com.google.protobuf.AbstractParser<File>() {
        public File parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new File(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<File> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string fileName = 1;
      public static final int FILENAME_FIELD_NUMBER = 1;
      private java.lang.Object fileName_;
      /**
       * <code>required string fileName = 1;</code>
       */
      public boolean hasFileName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string fileName = 1;</code>
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fileName_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string fileName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        fileName_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasFileName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getFileNameBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getFileNameBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.google.protobuf.ListProto.ListFilesResponse.File parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.google.protobuf.ListProto.ListFilesResponse.File parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.google.protobuf.ListProto.ListFilesResponse.File parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.google.protobuf.ListProto.ListFilesResponse.File parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.google.protobuf.ListProto.ListFilesResponse.File parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.google.protobuf.ListProto.ListFilesResponse.File parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.google.protobuf.ListProto.ListFilesResponse.File parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.google.protobuf.ListProto.ListFilesResponse.File parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.google.protobuf.ListProto.ListFilesResponse.File parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.google.protobuf.ListProto.ListFilesResponse.File parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.google.protobuf.ListProto.ListFilesResponse.File prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ds.hdfs.ListFilesResponse.File}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.google.protobuf.ListProto.ListFilesResponse.FileOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.google.protobuf.ListProto.internal_static_ds_hdfs_ListFilesResponse_File_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.google.protobuf.ListProto.internal_static_ds_hdfs_ListFilesResponse_File_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.google.protobuf.ListProto.ListFilesResponse.File.class, com.google.protobuf.ListProto.ListFilesResponse.File.Builder.class);
        }

        // Construct using com.google.protobuf.ListProto.ListFilesResponse.File.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          fileName_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.google.protobuf.ListProto.internal_static_ds_hdfs_ListFilesResponse_File_descriptor;
        }

        public com.google.protobuf.ListProto.ListFilesResponse.File getDefaultInstanceForType() {
          return com.google.protobuf.ListProto.ListFilesResponse.File.getDefaultInstance();
        }

        public com.google.protobuf.ListProto.ListFilesResponse.File build() {
          com.google.protobuf.ListProto.ListFilesResponse.File result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.google.protobuf.ListProto.ListFilesResponse.File buildPartial() {
          com.google.protobuf.ListProto.ListFilesResponse.File result = new com.google.protobuf.ListProto.ListFilesResponse.File(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.fileName_ = fileName_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.google.protobuf.ListProto.ListFilesResponse.File) {
            return mergeFrom((com.google.protobuf.ListProto.ListFilesResponse.File)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.google.protobuf.ListProto.ListFilesResponse.File other) {
          if (other == com.google.protobuf.ListProto.ListFilesResponse.File.getDefaultInstance()) return this;
          if (other.hasFileName()) {
            bitField0_ |= 0x00000001;
            fileName_ = other.fileName_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasFileName()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.ListProto.ListFilesResponse.File parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.google.protobuf.ListProto.ListFilesResponse.File) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string fileName = 1;
        private java.lang.Object fileName_ = "";
        /**
         * <code>required string fileName = 1;</code>
         */
        public boolean hasFileName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string fileName = 1;</code>
         */
        public java.lang.String getFileName() {
          java.lang.Object ref = fileName_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            fileName_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string fileName = 1;</code>
         */
        public com.google.protobuf.ByteString
            getFileNameBytes() {
          java.lang.Object ref = fileName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            fileName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string fileName = 1;</code>
         */
        public Builder setFileName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          fileName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string fileName = 1;</code>
         */
        public Builder clearFileName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          fileName_ = getDefaultInstance().getFileName();
          onChanged();
          return this;
        }
        /**
         * <code>required string fileName = 1;</code>
         */
        public Builder setFileNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          fileName_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:ds.hdfs.ListFilesResponse.File)
      }

      static {
        defaultInstance = new File(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:ds.hdfs.ListFilesResponse.File)
    }

    // repeated .ds.hdfs.ListFilesResponse.File files = 1;
    public static final int FILES_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ListProto.ListFilesResponse.File> files_;
    /**
     * <code>repeated .ds.hdfs.ListFilesResponse.File files = 1;</code>
     */
    public java.util.List<com.google.protobuf.ListProto.ListFilesResponse.File> getFilesList() {
      return files_;
    }
    /**
     * <code>repeated .ds.hdfs.ListFilesResponse.File files = 1;</code>
     */
    public java.util.List<? extends com.google.protobuf.ListProto.ListFilesResponse.FileOrBuilder> 
        getFilesOrBuilderList() {
      return files_;
    }
    /**
     * <code>repeated .ds.hdfs.ListFilesResponse.File files = 1;</code>
     */
    public int getFilesCount() {
      return files_.size();
    }
    /**
     * <code>repeated .ds.hdfs.ListFilesResponse.File files = 1;</code>
     */
    public com.google.protobuf.ListProto.ListFilesResponse.File getFiles(int index) {
      return files_.get(index);
    }
    /**
     * <code>repeated .ds.hdfs.ListFilesResponse.File files = 1;</code>
     */
    public com.google.protobuf.ListProto.ListFilesResponse.FileOrBuilder getFilesOrBuilder(
        int index) {
      return files_.get(index);
    }

    private void initFields() {
      files_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getFilesCount(); i++) {
        if (!getFiles(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < files_.size(); i++) {
        output.writeMessage(1, files_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < files_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, files_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.protobuf.ListProto.ListFilesResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.ListProto.ListFilesResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.ListProto.ListFilesResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.ListProto.ListFilesResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.ListProto.ListFilesResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protobuf.ListProto.ListFilesResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.protobuf.ListProto.ListFilesResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.protobuf.ListProto.ListFilesResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.protobuf.ListProto.ListFilesResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.protobuf.ListProto.ListFilesResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.protobuf.ListProto.ListFilesResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ds.hdfs.ListFilesResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.google.protobuf.ListProto.ListFilesResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.protobuf.ListProto.internal_static_ds_hdfs_ListFilesResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.protobuf.ListProto.internal_static_ds_hdfs_ListFilesResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.protobuf.ListProto.ListFilesResponse.class, com.google.protobuf.ListProto.ListFilesResponse.Builder.class);
      }

      // Construct using com.google.protobuf.ListProto.ListFilesResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFilesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (filesBuilder_ == null) {
          files_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          filesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.protobuf.ListProto.internal_static_ds_hdfs_ListFilesResponse_descriptor;
      }

      public com.google.protobuf.ListProto.ListFilesResponse getDefaultInstanceForType() {
        return com.google.protobuf.ListProto.ListFilesResponse.getDefaultInstance();
      }

      public com.google.protobuf.ListProto.ListFilesResponse build() {
        com.google.protobuf.ListProto.ListFilesResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.protobuf.ListProto.ListFilesResponse buildPartial() {
        com.google.protobuf.ListProto.ListFilesResponse result = new com.google.protobuf.ListProto.ListFilesResponse(this);
        int from_bitField0_ = bitField0_;
        if (filesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            files_ = java.util.Collections.unmodifiableList(files_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.files_ = files_;
        } else {
          result.files_ = filesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.protobuf.ListProto.ListFilesResponse) {
          return mergeFrom((com.google.protobuf.ListProto.ListFilesResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.protobuf.ListProto.ListFilesResponse other) {
        if (other == com.google.protobuf.ListProto.ListFilesResponse.getDefaultInstance()) return this;
        if (filesBuilder_ == null) {
          if (!other.files_.isEmpty()) {
            if (files_.isEmpty()) {
              files_ = other.files_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureFilesIsMutable();
              files_.addAll(other.files_);
            }
            onChanged();
          }
        } else {
          if (!other.files_.isEmpty()) {
            if (filesBuilder_.isEmpty()) {
              filesBuilder_.dispose();
              filesBuilder_ = null;
              files_ = other.files_;
              bitField0_ = (bitField0_ & ~0x00000001);
              filesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFilesFieldBuilder() : null;
            } else {
              filesBuilder_.addAllMessages(other.files_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getFilesCount(); i++) {
          if (!getFiles(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.ListProto.ListFilesResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.protobuf.ListProto.ListFilesResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .ds.hdfs.ListFilesResponse.File files = 1;
      private java.util.List<com.google.protobuf.ListProto.ListFilesResponse.File> files_ =
        java.util.Collections.emptyList();
      private void ensureFilesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          files_ = new java.util.ArrayList<com.google.protobuf.ListProto.ListFilesResponse.File>(files_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.google.protobuf.ListProto.ListFilesResponse.File, com.google.protobuf.ListProto.ListFilesResponse.File.Builder, com.google.protobuf.ListProto.ListFilesResponse.FileOrBuilder> filesBuilder_;

      /**
       * <code>repeated .ds.hdfs.ListFilesResponse.File files = 1;</code>
       */
      public java.util.List<com.google.protobuf.ListProto.ListFilesResponse.File> getFilesList() {
        if (filesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(files_);
        } else {
          return filesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ds.hdfs.ListFilesResponse.File files = 1;</code>
       */
      public int getFilesCount() {
        if (filesBuilder_ == null) {
          return files_.size();
        } else {
          return filesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ds.hdfs.ListFilesResponse.File files = 1;</code>
       */
      public com.google.protobuf.ListProto.ListFilesResponse.File getFiles(int index) {
        if (filesBuilder_ == null) {
          return files_.get(index);
        } else {
          return filesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ds.hdfs.ListFilesResponse.File files = 1;</code>
       */
      public Builder setFiles(
          int index, com.google.protobuf.ListProto.ListFilesResponse.File value) {
        if (filesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFilesIsMutable();
          files_.set(index, value);
          onChanged();
        } else {
          filesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ds.hdfs.ListFilesResponse.File files = 1;</code>
       */
      public Builder setFiles(
          int index, com.google.protobuf.ListProto.ListFilesResponse.File.Builder builderForValue) {
        if (filesBuilder_ == null) {
          ensureFilesIsMutable();
          files_.set(index, builderForValue.build());
          onChanged();
        } else {
          filesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ds.hdfs.ListFilesResponse.File files = 1;</code>
       */
      public Builder addFiles(com.google.protobuf.ListProto.ListFilesResponse.File value) {
        if (filesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFilesIsMutable();
          files_.add(value);
          onChanged();
        } else {
          filesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ds.hdfs.ListFilesResponse.File files = 1;</code>
       */
      public Builder addFiles(
          int index, com.google.protobuf.ListProto.ListFilesResponse.File value) {
        if (filesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFilesIsMutable();
          files_.add(index, value);
          onChanged();
        } else {
          filesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ds.hdfs.ListFilesResponse.File files = 1;</code>
       */
      public Builder addFiles(
          com.google.protobuf.ListProto.ListFilesResponse.File.Builder builderForValue) {
        if (filesBuilder_ == null) {
          ensureFilesIsMutable();
          files_.add(builderForValue.build());
          onChanged();
        } else {
          filesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ds.hdfs.ListFilesResponse.File files = 1;</code>
       */
      public Builder addFiles(
          int index, com.google.protobuf.ListProto.ListFilesResponse.File.Builder builderForValue) {
        if (filesBuilder_ == null) {
          ensureFilesIsMutable();
          files_.add(index, builderForValue.build());
          onChanged();
        } else {
          filesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ds.hdfs.ListFilesResponse.File files = 1;</code>
       */
      public Builder addAllFiles(
          java.lang.Iterable<? extends com.google.protobuf.ListProto.ListFilesResponse.File> values) {
        if (filesBuilder_ == null) {
          ensureFilesIsMutable();
          super.addAll(values, files_);
          onChanged();
        } else {
          filesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ds.hdfs.ListFilesResponse.File files = 1;</code>
       */
      public Builder clearFiles() {
        if (filesBuilder_ == null) {
          files_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          filesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ds.hdfs.ListFilesResponse.File files = 1;</code>
       */
      public Builder removeFiles(int index) {
        if (filesBuilder_ == null) {
          ensureFilesIsMutable();
          files_.remove(index);
          onChanged();
        } else {
          filesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ds.hdfs.ListFilesResponse.File files = 1;</code>
       */
      public com.google.protobuf.ListProto.ListFilesResponse.File.Builder getFilesBuilder(
          int index) {
        return getFilesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ds.hdfs.ListFilesResponse.File files = 1;</code>
       */
      public com.google.protobuf.ListProto.ListFilesResponse.FileOrBuilder getFilesOrBuilder(
          int index) {
        if (filesBuilder_ == null) {
          return files_.get(index);  } else {
          return filesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ds.hdfs.ListFilesResponse.File files = 1;</code>
       */
      public java.util.List<? extends com.google.protobuf.ListProto.ListFilesResponse.FileOrBuilder> 
           getFilesOrBuilderList() {
        if (filesBuilder_ != null) {
          return filesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(files_);
        }
      }
      /**
       * <code>repeated .ds.hdfs.ListFilesResponse.File files = 1;</code>
       */
      public com.google.protobuf.ListProto.ListFilesResponse.File.Builder addFilesBuilder() {
        return getFilesFieldBuilder().addBuilder(
            com.google.protobuf.ListProto.ListFilesResponse.File.getDefaultInstance());
      }
      /**
       * <code>repeated .ds.hdfs.ListFilesResponse.File files = 1;</code>
       */
      public com.google.protobuf.ListProto.ListFilesResponse.File.Builder addFilesBuilder(
          int index) {
        return getFilesFieldBuilder().addBuilder(
            index, com.google.protobuf.ListProto.ListFilesResponse.File.getDefaultInstance());
      }
      /**
       * <code>repeated .ds.hdfs.ListFilesResponse.File files = 1;</code>
       */
      public java.util.List<com.google.protobuf.ListProto.ListFilesResponse.File.Builder> 
           getFilesBuilderList() {
        return getFilesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.google.protobuf.ListProto.ListFilesResponse.File, com.google.protobuf.ListProto.ListFilesResponse.File.Builder, com.google.protobuf.ListProto.ListFilesResponse.FileOrBuilder> 
          getFilesFieldBuilder() {
        if (filesBuilder_ == null) {
          filesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.google.protobuf.ListProto.ListFilesResponse.File, com.google.protobuf.ListProto.ListFilesResponse.File.Builder, com.google.protobuf.ListProto.ListFilesResponse.FileOrBuilder>(
                  files_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          files_ = null;
        }
        return filesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ds.hdfs.ListFilesResponse)
    }

    static {
      defaultInstance = new ListFilesResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ds.hdfs.ListFilesResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_hdfs_ListFilesResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ds_hdfs_ListFilesResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_hdfs_ListFilesResponse_File_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ds_hdfs_ListFilesResponse_File_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ds/hdfs/list.proto\022\007ds.hdfs\"]\n\021ListFil" +
      "esResponse\022.\n\005files\030\001 \003(\0132\037.ds.hdfs.List" +
      "FilesResponse.File\032\030\n\004File\022\020\n\010fileName\030\001" +
      " \002(\tB \n\023com.google.protobufB\tListProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ds_hdfs_ListFilesResponse_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ds_hdfs_ListFilesResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ds_hdfs_ListFilesResponse_descriptor,
              new java.lang.String[] { "Files", });
          internal_static_ds_hdfs_ListFilesResponse_File_descriptor =
            internal_static_ds_hdfs_ListFilesResponse_descriptor.getNestedTypes().get(0);
          internal_static_ds_hdfs_ListFilesResponse_File_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ds_hdfs_ListFilesResponse_File_descriptor,
              new java.lang.String[] { "FileName", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
