version: '3.7'
services:
  namenode:
    image: roshni/distributed_hdfs
    volumes:
      - ./src:/src
    ports:
      - "9090:9090"
    networks:
      - hadoopnet
    environment:
      - NAMENODE_NAME=NameNode
      - NAMENODE_PORT=9090
      - NAMENODE_IP=namenode 
    entrypoint: /app/run_docker.sh -n
    tty: true

  dataNode1:
    image: roshni/distributed_hdfs
    volumes:
      - ./src:/src
    networks:
      - hadoopnet
    entrypoint: bash -c /app/run_docker.sh -d
    tty: true
    environment:
      - NODE_NAME=DataNode1
      - NODE_ID=0
      - NODE_PORT=9092
      - NAMENODE_IP=namenode
      - NAMENODE_PORT=9090
      - NAMENODE_NAME=NameNode
    ports:
      - "9092:9092"

  dataNode2:
    image: roshni/distributed_hdfs
    networks:
      - hadoopnet
    tty: true
    entrypoint: /app/run_docker.sh -d
    environment:
      - NODE_NAME=DataNode2
      - NODE_ID=1
      - NODE_PORT=9093
      - NAMENODE_IP=namenode
      - NAMENODE_PORT=9090
      - NAMENODE_NAME=NameNode
    ports:
      - "9093:9093"

  dataNode3:
    image: roshni/distributed_hdfs
    networks:
      - hadoopnet
    tty: true
    entrypoint: /app/run_docker.sh -d
    environment:
      - NODE_NAME=DataNode3
      - NODE_ID=2
      - NODE_PORT=9094
      - NAMENODE_IP=namenode
      - NAMENODE_PORT=9090
      - NAMENODE_NAME=NameNode
    ports:
      - "9094:9094"
networks:
  hadoopnet:
    name: hadoopnet
