// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ds/hdfs/recoverDataNode.proto

package com.google.protobuf;

public final class RecoverDataNodeProto {
  private RecoverDataNodeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RecoverDataNodeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ds.hdfs.RecoverDataNode)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, .ds.hdfs.RecoverDataNode.ListBlocks&gt; files = 1;</code>
     */
    int getFilesCount();
    /**
     * <code>map&lt;string, .ds.hdfs.RecoverDataNode.ListBlocks&gt; files = 1;</code>
     */
    boolean containsFiles(
        java.lang.String key);
    /**
     * Use {@link #getFilesMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks>
    getFiles();
    /**
     * <code>map&lt;string, .ds.hdfs.RecoverDataNode.ListBlocks&gt; files = 1;</code>
     */
    java.util.Map<java.lang.String, com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks>
    getFilesMap();
    /**
     * <code>map&lt;string, .ds.hdfs.RecoverDataNode.ListBlocks&gt; files = 1;</code>
     */

    com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks getFilesOrDefault(
        java.lang.String key,
        com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks defaultValue);
    /**
     * <code>map&lt;string, .ds.hdfs.RecoverDataNode.ListBlocks&gt; files = 1;</code>
     */

    com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks getFilesOrThrow(
        java.lang.String key);

    /**
     * <code>required int32 status = 3;</code>
     * @return Whether the status field is set.
     */
    boolean hasStatus();
    /**
     * <code>required int32 status = 3;</code>
     * @return The status.
     */
    int getStatus();
  }
  /**
   * Protobuf type {@code ds.hdfs.RecoverDataNode}
   */
  public  static final class RecoverDataNode extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ds.hdfs.RecoverDataNode)
      RecoverDataNodeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RecoverDataNode.newBuilder() to construct.
    private RecoverDataNode(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RecoverDataNode() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RecoverDataNode();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RecoverDataNode(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                files_ = com.google.protobuf.MapField.newMapField(
                    FilesDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks>
              files__ = input.readMessage(
                  FilesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              files_.getMutableMap().put(
                  files__.getKey(), files__.getValue());
              break;
            }
            case 24: {
              bitField0_ |= 0x00000001;
              status_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.protobuf.RecoverDataNodeProto.internal_static_ds_hdfs_RecoverDataNode_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetFiles();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.protobuf.RecoverDataNodeProto.internal_static_ds_hdfs_RecoverDataNode_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.class, com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.Builder.class);
    }

    public interface ListBlocksOrBuilder extends
        // @@protoc_insertion_point(interface_extends:ds.hdfs.RecoverDataNode.ListBlocks)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>repeated int32 blockNumber = 1;</code>
       * @return A list containing the blockNumber.
       */
      java.util.List<java.lang.Integer> getBlockNumberList();
      /**
       * <code>repeated int32 blockNumber = 1;</code>
       * @return The count of blockNumber.
       */
      int getBlockNumberCount();
      /**
       * <code>repeated int32 blockNumber = 1;</code>
       * @param index The index of the element to return.
       * @return The blockNumber at the given index.
       */
      int getBlockNumber(int index);
    }
    /**
     * Protobuf type {@code ds.hdfs.RecoverDataNode.ListBlocks}
     */
    public  static final class ListBlocks extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:ds.hdfs.RecoverDataNode.ListBlocks)
        ListBlocksOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use ListBlocks.newBuilder() to construct.
      private ListBlocks(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private ListBlocks() {
        blockNumber_ = emptyIntList();
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new ListBlocks();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private ListBlocks(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                  blockNumber_ = newIntList();
                  mutable_bitField0_ |= 0x00000001;
                }
                blockNumber_.addInt(input.readInt32());
                break;
              }
              case 10: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                  blockNumber_ = newIntList();
                  mutable_bitField0_ |= 0x00000001;
                }
                while (input.getBytesUntilLimit() > 0) {
                  blockNumber_.addInt(input.readInt32());
                }
                input.popLimit(limit);
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) != 0)) {
            blockNumber_.makeImmutable(); // C
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.protobuf.RecoverDataNodeProto.internal_static_ds_hdfs_RecoverDataNode_ListBlocks_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.protobuf.RecoverDataNodeProto.internal_static_ds_hdfs_RecoverDataNode_ListBlocks_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks.class, com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks.Builder.class);
      }

      public static final int BLOCKNUMBER_FIELD_NUMBER = 1;
      private com.google.protobuf.Internal.IntList blockNumber_;
      /**
       * <code>repeated int32 blockNumber = 1;</code>
       * @return A list containing the blockNumber.
       */
      public java.util.List<java.lang.Integer>
          getBlockNumberList() {
        return blockNumber_;
      }
      /**
       * <code>repeated int32 blockNumber = 1;</code>
       * @return The count of blockNumber.
       */
      public int getBlockNumberCount() {
        return blockNumber_.size();
      }
      /**
       * <code>repeated int32 blockNumber = 1;</code>
       * @param index The index of the element to return.
       * @return The blockNumber at the given index.
       */
      public int getBlockNumber(int index) {
        return blockNumber_.getInt(index);
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        for (int i = 0; i < blockNumber_.size(); i++) {
          output.writeInt32(1, blockNumber_.getInt(i));
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        {
          int dataSize = 0;
          for (int i = 0; i < blockNumber_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(blockNumber_.getInt(i));
          }
          size += dataSize;
          size += 1 * getBlockNumberList().size();
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks)) {
          return super.equals(obj);
        }
        com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks other = (com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks) obj;

        if (!getBlockNumberList()
            .equals(other.getBlockNumberList())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (getBlockNumberCount() > 0) {
          hash = (37 * hash) + BLOCKNUMBER_FIELD_NUMBER;
          hash = (53 * hash) + getBlockNumberList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ds.hdfs.RecoverDataNode.ListBlocks}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:ds.hdfs.RecoverDataNode.ListBlocks)
          com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocksOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.google.protobuf.RecoverDataNodeProto.internal_static_ds_hdfs_RecoverDataNode_ListBlocks_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.google.protobuf.RecoverDataNodeProto.internal_static_ds_hdfs_RecoverDataNode_ListBlocks_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks.class, com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks.Builder.class);
        }

        // Construct using com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          blockNumber_ = emptyIntList();
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.google.protobuf.RecoverDataNodeProto.internal_static_ds_hdfs_RecoverDataNode_ListBlocks_descriptor;
        }

        @java.lang.Override
        public com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks getDefaultInstanceForType() {
          return com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks.getDefaultInstance();
        }

        @java.lang.Override
        public com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks build() {
          com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks buildPartial() {
          com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks result = new com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks(this);
          int from_bitField0_ = bitField0_;
          if (((bitField0_ & 0x00000001) != 0)) {
            blockNumber_.makeImmutable();
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.blockNumber_ = blockNumber_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks) {
            return mergeFrom((com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks other) {
          if (other == com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks.getDefaultInstance()) return this;
          if (!other.blockNumber_.isEmpty()) {
            if (blockNumber_.isEmpty()) {
              blockNumber_ = other.blockNumber_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBlockNumberIsMutable();
              blockNumber_.addAll(other.blockNumber_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private com.google.protobuf.Internal.IntList blockNumber_ = emptyIntList();
        private void ensureBlockNumberIsMutable() {
          if (!((bitField0_ & 0x00000001) != 0)) {
            blockNumber_ = mutableCopy(blockNumber_);
            bitField0_ |= 0x00000001;
           }
        }
        /**
         * <code>repeated int32 blockNumber = 1;</code>
         * @return A list containing the blockNumber.
         */
        public java.util.List<java.lang.Integer>
            getBlockNumberList() {
          return ((bitField0_ & 0x00000001) != 0) ?
                   java.util.Collections.unmodifiableList(blockNumber_) : blockNumber_;
        }
        /**
         * <code>repeated int32 blockNumber = 1;</code>
         * @return The count of blockNumber.
         */
        public int getBlockNumberCount() {
          return blockNumber_.size();
        }
        /**
         * <code>repeated int32 blockNumber = 1;</code>
         * @param index The index of the element to return.
         * @return The blockNumber at the given index.
         */
        public int getBlockNumber(int index) {
          return blockNumber_.getInt(index);
        }
        /**
         * <code>repeated int32 blockNumber = 1;</code>
         * @param index The index to set the value at.
         * @param value The blockNumber to set.
         * @return This builder for chaining.
         */
        public Builder setBlockNumber(
            int index, int value) {
          ensureBlockNumberIsMutable();
          blockNumber_.setInt(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated int32 blockNumber = 1;</code>
         * @param value The blockNumber to add.
         * @return This builder for chaining.
         */
        public Builder addBlockNumber(int value) {
          ensureBlockNumberIsMutable();
          blockNumber_.addInt(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated int32 blockNumber = 1;</code>
         * @param values The blockNumber to add.
         * @return This builder for chaining.
         */
        public Builder addAllBlockNumber(
            java.lang.Iterable<? extends java.lang.Integer> values) {
          ensureBlockNumberIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, blockNumber_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated int32 blockNumber = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearBlockNumber() {
          blockNumber_ = emptyIntList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:ds.hdfs.RecoverDataNode.ListBlocks)
      }

      // @@protoc_insertion_point(class_scope:ds.hdfs.RecoverDataNode.ListBlocks)
      private static final com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks();
      }

      public static com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<ListBlocks>
          PARSER = new com.google.protobuf.AbstractParser<ListBlocks>() {
        @java.lang.Override
        public ListBlocks parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new ListBlocks(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<ListBlocks> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<ListBlocks> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int FILES_FIELD_NUMBER = 1;
    private static final class FilesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks>newDefaultInstance(
                  com.google.protobuf.RecoverDataNodeProto.internal_static_ds_hdfs_RecoverDataNode_FilesEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks> files_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks>
    internalGetFiles() {
      if (files_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            FilesDefaultEntryHolder.defaultEntry);
      }
      return files_;
    }

    public int getFilesCount() {
      return internalGetFiles().getMap().size();
    }
    /**
     * <code>map&lt;string, .ds.hdfs.RecoverDataNode.ListBlocks&gt; files = 1;</code>
     */

    public boolean containsFiles(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetFiles().getMap().containsKey(key);
    }
    /**
     * Use {@link #getFilesMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks> getFiles() {
      return getFilesMap();
    }
    /**
     * <code>map&lt;string, .ds.hdfs.RecoverDataNode.ListBlocks&gt; files = 1;</code>
     */

    public java.util.Map<java.lang.String, com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks> getFilesMap() {
      return internalGetFiles().getMap();
    }
    /**
     * <code>map&lt;string, .ds.hdfs.RecoverDataNode.ListBlocks&gt; files = 1;</code>
     */

    public com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks getFilesOrDefault(
        java.lang.String key,
        com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks> map =
          internalGetFiles().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .ds.hdfs.RecoverDataNode.ListBlocks&gt; files = 1;</code>
     */

    public com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks getFilesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks> map =
          internalGetFiles().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int STATUS_FIELD_NUMBER = 3;
    private int status_;
    /**
     * <code>required int32 status = 3;</code>
     * @return Whether the status field is set.
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 status = 3;</code>
     * @return The status.
     */
    public int getStatus() {
      return status_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetFiles(),
          FilesDefaultEntryHolder.defaultEntry,
          1);
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(3, status_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks> entry
           : internalGetFiles().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks>
        files__ = FilesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, files__);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, status_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.protobuf.RecoverDataNodeProto.RecoverDataNode)) {
        return super.equals(obj);
      }
      com.google.protobuf.RecoverDataNodeProto.RecoverDataNode other = (com.google.protobuf.RecoverDataNodeProto.RecoverDataNode) obj;

      if (!internalGetFiles().equals(
          other.internalGetFiles())) return false;
      if (hasStatus() != other.hasStatus()) return false;
      if (hasStatus()) {
        if (getStatus()
            != other.getStatus()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetFiles().getMap().isEmpty()) {
        hash = (37 * hash) + FILES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetFiles().hashCode();
      }
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.protobuf.RecoverDataNodeProto.RecoverDataNode parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.RecoverDataNodeProto.RecoverDataNode parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.RecoverDataNodeProto.RecoverDataNode parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.RecoverDataNodeProto.RecoverDataNode parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.RecoverDataNodeProto.RecoverDataNode parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.RecoverDataNodeProto.RecoverDataNode parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.RecoverDataNodeProto.RecoverDataNode parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.protobuf.RecoverDataNodeProto.RecoverDataNode parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.protobuf.RecoverDataNodeProto.RecoverDataNode parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.protobuf.RecoverDataNodeProto.RecoverDataNode parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.protobuf.RecoverDataNodeProto.RecoverDataNode parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.protobuf.RecoverDataNodeProto.RecoverDataNode parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.protobuf.RecoverDataNodeProto.RecoverDataNode prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ds.hdfs.RecoverDataNode}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ds.hdfs.RecoverDataNode)
        com.google.protobuf.RecoverDataNodeProto.RecoverDataNodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.protobuf.RecoverDataNodeProto.internal_static_ds_hdfs_RecoverDataNode_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetFiles();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableFiles();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.protobuf.RecoverDataNodeProto.internal_static_ds_hdfs_RecoverDataNode_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.class, com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.Builder.class);
      }

      // Construct using com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        internalGetMutableFiles().clear();
        status_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.protobuf.RecoverDataNodeProto.internal_static_ds_hdfs_RecoverDataNode_descriptor;
      }

      @java.lang.Override
      public com.google.protobuf.RecoverDataNodeProto.RecoverDataNode getDefaultInstanceForType() {
        return com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.protobuf.RecoverDataNodeProto.RecoverDataNode build() {
        com.google.protobuf.RecoverDataNodeProto.RecoverDataNode result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.protobuf.RecoverDataNodeProto.RecoverDataNode buildPartial() {
        com.google.protobuf.RecoverDataNodeProto.RecoverDataNode result = new com.google.protobuf.RecoverDataNodeProto.RecoverDataNode(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.files_ = internalGetFiles();
        result.files_.makeImmutable();
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.status_ = status_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.protobuf.RecoverDataNodeProto.RecoverDataNode) {
          return mergeFrom((com.google.protobuf.RecoverDataNodeProto.RecoverDataNode)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.protobuf.RecoverDataNodeProto.RecoverDataNode other) {
        if (other == com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.getDefaultInstance()) return this;
        internalGetMutableFiles().mergeFrom(
            other.internalGetFiles());
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasStatus()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.RecoverDataNodeProto.RecoverDataNode parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.protobuf.RecoverDataNodeProto.RecoverDataNode) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks> files_;
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks>
      internalGetFiles() {
        if (files_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              FilesDefaultEntryHolder.defaultEntry);
        }
        return files_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks>
      internalGetMutableFiles() {
        onChanged();;
        if (files_ == null) {
          files_ = com.google.protobuf.MapField.newMapField(
              FilesDefaultEntryHolder.defaultEntry);
        }
        if (!files_.isMutable()) {
          files_ = files_.copy();
        }
        return files_;
      }

      public int getFilesCount() {
        return internalGetFiles().getMap().size();
      }
      /**
       * <code>map&lt;string, .ds.hdfs.RecoverDataNode.ListBlocks&gt; files = 1;</code>
       */

      public boolean containsFiles(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetFiles().getMap().containsKey(key);
      }
      /**
       * Use {@link #getFilesMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks> getFiles() {
        return getFilesMap();
      }
      /**
       * <code>map&lt;string, .ds.hdfs.RecoverDataNode.ListBlocks&gt; files = 1;</code>
       */

      public java.util.Map<java.lang.String, com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks> getFilesMap() {
        return internalGetFiles().getMap();
      }
      /**
       * <code>map&lt;string, .ds.hdfs.RecoverDataNode.ListBlocks&gt; files = 1;</code>
       */

      public com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks getFilesOrDefault(
          java.lang.String key,
          com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks> map =
            internalGetFiles().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .ds.hdfs.RecoverDataNode.ListBlocks&gt; files = 1;</code>
       */

      public com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks getFilesOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks> map =
            internalGetFiles().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearFiles() {
        internalGetMutableFiles().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .ds.hdfs.RecoverDataNode.ListBlocks&gt; files = 1;</code>
       */

      public Builder removeFiles(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableFiles().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks>
      getMutableFiles() {
        return internalGetMutableFiles().getMutableMap();
      }
      /**
       * <code>map&lt;string, .ds.hdfs.RecoverDataNode.ListBlocks&gt; files = 1;</code>
       */
      public Builder putFiles(
          java.lang.String key,
          com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableFiles().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .ds.hdfs.RecoverDataNode.ListBlocks&gt; files = 1;</code>
       */

      public Builder putAllFiles(
          java.util.Map<java.lang.String, com.google.protobuf.RecoverDataNodeProto.RecoverDataNode.ListBlocks> values) {
        internalGetMutableFiles().getMutableMap()
            .putAll(values);
        return this;
      }

      private int status_ ;
      /**
       * <code>required int32 status = 3;</code>
       * @return Whether the status field is set.
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 status = 3;</code>
       * @return The status.
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>required int32 status = 3;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(int value) {
        bitField0_ |= 0x00000002;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 status = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        status_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ds.hdfs.RecoverDataNode)
    }

    // @@protoc_insertion_point(class_scope:ds.hdfs.RecoverDataNode)
    private static final com.google.protobuf.RecoverDataNodeProto.RecoverDataNode DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.protobuf.RecoverDataNodeProto.RecoverDataNode();
    }

    public static com.google.protobuf.RecoverDataNodeProto.RecoverDataNode getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<RecoverDataNode>
        PARSER = new com.google.protobuf.AbstractParser<RecoverDataNode>() {
      @java.lang.Override
      public RecoverDataNode parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RecoverDataNode(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RecoverDataNode> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RecoverDataNode> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.RecoverDataNodeProto.RecoverDataNode getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_hdfs_RecoverDataNode_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_hdfs_RecoverDataNode_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_hdfs_RecoverDataNode_ListBlocks_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_hdfs_RecoverDataNode_ListBlocks_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_hdfs_RecoverDataNode_FilesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_hdfs_RecoverDataNode_FilesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035ds/hdfs/recoverDataNode.proto\022\007ds.hdfs" +
      "\"\313\001\n\017RecoverDataNode\0222\n\005files\030\001 \003(\0132#.ds" +
      ".hdfs.RecoverDataNode.FilesEntry\022\016\n\006stat" +
      "us\030\003 \002(\005\032!\n\nListBlocks\022\023\n\013blockNumber\030\001 " +
      "\003(\005\032Q\n\nFilesEntry\022\013\n\003key\030\001 \001(\t\0222\n\005value\030" +
      "\002 \001(\0132#.ds.hdfs.RecoverDataNode.ListBloc" +
      "ks:\0028\001B+\n\023com.google.protobufB\024RecoverDa" +
      "taNodeProto"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ds_hdfs_RecoverDataNode_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ds_hdfs_RecoverDataNode_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_hdfs_RecoverDataNode_descriptor,
        new java.lang.String[] { "Files", "Status", });
    internal_static_ds_hdfs_RecoverDataNode_ListBlocks_descriptor =
      internal_static_ds_hdfs_RecoverDataNode_descriptor.getNestedTypes().get(0);
    internal_static_ds_hdfs_RecoverDataNode_ListBlocks_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_hdfs_RecoverDataNode_ListBlocks_descriptor,
        new java.lang.String[] { "BlockNumber", });
    internal_static_ds_hdfs_RecoverDataNode_FilesEntry_descriptor =
      internal_static_ds_hdfs_RecoverDataNode_descriptor.getNestedTypes().get(1);
    internal_static_ds_hdfs_RecoverDataNode_FilesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_hdfs_RecoverDataNode_FilesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
